  - title: "Register for Corporation Tax"
    url: "/corporation-tax"
    description: "You need to register for corporation tax within 3 months of starting to do business, if you haven’t done so already."
    section_name: "Business tax"
  - title: "Avoid anti-competitive activity"
    url: "/cartels-price-fixing/types-of-anticompetitive-activity"
    description: "You need to understand rules around price-fixing and competition."
    section_name: "Competition law"
  - title: "Dealing with personal information"
    url: "/data-protection-your-business"
    description: "If your business stores anyone’s personal information, you need to know how to look after it."
    section_name: "Data protection"
  - title: "Check if you need to send a Self Assessment"
    url: "/check-if-you-need-tax-return"
    description: "You might need to send a tax return if you have any untaxed income, such as dividends."
    section_name: "Personal tax"
  - title: "Health and safety at work"
    url: "https://www.hse.gov.uk/guidance/index.htm"
    description: "How to keep your employees and customers safe."
    section_name: "Health and safety"
  - title: "Starting a business guidance"
    url: "/browse/business/setting-up"
    description: "Information about starting and growing your business."
    section_name: "Running a business"
